#################################
#  Email info
#  Max of 5 entries each 
#  for smptto, smptcc and smptbcc
#################################
#
smtpfrom   Mikes Study <mike@kirrawee.net>    
#smtpto     Greg McCall <emailgregnow@gmail.com>
#smtpto     Mike Kelly <gronk1774@gmail.com>
#smtpto    Greg Ford <greg@aussiesky.net>     
smtpto    Mikes Gmail <gronk1774@gmail.com>  
pingip    192.168.1.11
#
# Minimum delay before activating initial roof close
#
#delay     1830  production
delay 400 for test only
# Minimum interval between roof closes
#
interval  3600
#

