#################################
#  Email info
#  Max of 5 entries each 
#  for smptto, smptcc and smptbcc
#################################
#
smtpfrom   Mikes Study <mike@example.net>    
#smtpto     McCall <gregnow@example.nwt>
#smtpto     Mike Gissane <gronk1774@example.com>
#smtpto    Greg Cole <greg@example.net>     
smtpto    Mikes Email <gronk1774@example.com>  
pingip    192.168.1.11
#
# Minimum delay before activating initial router reset
#
#delay     1830  production
delay 400 for test only
# Minimum interval between roof closes
#
interval  3600
#

